---
- hosts: web
  tasks:
   - name: Installing nginx
     apt: allow_unauthenticated=yes name=nginx state=present

   - name: Installing letsencrypt
     apt: allow_unauthenticated=yes name=letsencrypt state=present

   - name: Removing default sites-Available
     file: path=/etc/nginx/sites-available/default state=absent
   - name: Removing default sites-Enabled
     file: path=/etc/nginx/sites-enabled/default state=absent

   - name: Installing nginx configuration
     template: src=xsavitsky.devops.srwx.net.conf.j2 dest=/etc/nginx/sites-available/xsavitsky.devops.srwx.net.conf owner=root group=root mode=0644
     notify: restart nginx

   - name: Creating symlink to sites-enabled nginx
     command: ln -s /etc/nginx/sites-available/xsavitsky.devops.srwx.net.conf /etc/nginx/sites-enabled/ warn=no
     args:
      creates: /etc/nginx/sites-enabled/
     notify: restart nginx

  handlers:
   - name: restart nginx
     service: name=nginx state=restarted
